// This file is deprecated.
// The active Service Worker is located in public/sw.js and will be copied to the root ./sw.js during the build process.
// Please do not edit this file.
console.log("This service worker file is deprecated. Use public/sw.js instead.");
